import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy & consent",
  description: "How RARELINK handles donor consent, contact details and analytics.",
};

export const dynamic = "force-dynamic";

const SECTIONS = [
  {
    title: "What we collect",
    body: [
      "Donor registration: display name, blood group, city, contact details and your consent timestamp.",
      "Emergency requests: blood group, component, units, city and a contact handle — never a patient's name, age, diagnosis or identity.",
      "Chat sessions: your messages in the current conversation, used only to remember context such as blood group and city.",
      "Privacy-safe product events (search started, call clicked, request fulfilled) with no medical or personal identifiers.",
    ],
  },
  {
    title: "What is never collected",
    body: [
      "Aadhaar, ABHA or any government identifier — there is no legal or operational need for it here.",
      "Medical history, diagnosis, transfusion records or hospital patient data.",
      "Donor home addresses — only area-level coordinates are stored, and public results round them further.",
    ],
  },
  {
    title: "How donor contact works",
    body: [
      "Phone and email are stored privately and are excluded from the public SQL projection used by search.",
      "A requester leaves their own handle and a short note; the donor decides whether to respond.",
      "Contact details are never returned by an API response, a search result, an export or a log line.",
      "Emergency alerts are opt-in, respect opt-out, daily limits and quiet hours.",
    ],
  },
  {
    title: "Verification & retention",
    body: [
      "Verification states: VERIFIED, PENDING, EXPIRED, SUSPENDED — with an audit record for every change.",
      "Self-reported blood groups are labelled as such and are never presented as medically confirmed.",
      "You can withdraw consent or delete your record at any time; deletion removes contact details and removes you from search.",
    ],
  },
  {
    title: "What we don't log",
    body: [
      "Passwords, OTPs, API keys, government identifiers or donor private fields.",
      "Analytics metadata is filtered by key name, and string values are truncated.",
    ],
  },
  {
    title: "Third parties",
    body: [
      "Map tiles and data © OpenStreetMap contributors. Geocoding uses a bundled gazetteer by default — the public Nominatim instance is not used for bulk search.",
      "If an AI model provider is configured, only your message text and conversation context are sent; results are generated by the backend before any summary is written.",
    ],
  },
];

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-10 sm:px-6">
      <p className="text-xs font-semibold uppercase tracking-[0.18em] text-brand">Privacy</p>
      <h1 className="mt-1 text-3xl font-bold tracking-tight text-ink">Privacy &amp; consent</h1>
      <p className="mt-3 text-sm leading-relaxed text-ink-soft">
        RARELINK is designed around the principle of collecting the minimum necessary. This page
        describes the practice, not just the intent.
      </p>

      <div className="mt-8 space-y-4">
        {SECTIONS.map((s) => (
          <section key={s.title} className="card p-5">
            <h2 className="font-semibold text-ink">{s.title}</h2>
            <ul className="mt-2.5 space-y-2 text-sm leading-relaxed text-ink-soft">
              {s.body.map((line) => (
                <li key={line} className="flex gap-2">
                  <span className="text-brand" aria-hidden="true">•</span>
                  <span>{line}</span>
                </li>
              ))}
            </ul>
          </section>
        ))}
      </div>

      <p className="mt-6 rounded-xl bg-canvas px-4 py-3 text-xs leading-relaxed text-ink-mute">
        This build is a hackathon prototype. A production deployment would add OTP/session
        authentication, encryption at rest for contact fields, a formal data-retention schedule and
        a consent-withdrawal workflow, and would be reviewed against applicable Indian
        data-protection requirements before handling real personal data.
      </p>

      <div className="mt-6 flex gap-2">
        <Link href="/donors#register" className="inline-flex h-10 items-center rounded-xl bg-navy px-4 text-sm font-semibold text-white">
          Manage your registration
        </Link>
        <Link href="/about" className="inline-flex h-10 items-center rounded-xl border border-line px-4 text-sm font-semibold text-ink">
          How it works
        </Link>
      </div>
    </div>
  );
}
